### ISSUE TITLE
Step 4/5 : COPY ../../datagenerator /opt/dagster/datagenerator COPY failed: forbidden path outside the build context: ../../datagenerator () ERROR: Service 'data_generator' failed to build : Build failed

### ISSUE THREAD

**Issue by mbiombani** [josephmachado/online_store#1]
i joseph, i have a error with docker-compose up --build

Step 4/5 : COPY ../../datagenerator /opt/dagster/datagenerator
COPY failed: forbidden path outside the build context: ../../datagenerator ()
ERROR: Service 'data_generator' failed to build : Build failed

**Comment by josephmachado** [comment]
Hey @mbiombani  thank you for opening an issue. Can you let me know if
1. you use windows/linux/mac os?
2. are in the online_store directory

and can you please paste the commands you used from git clone to the one that produced this message?

**Comment by mbiombani** [comment]
1-Ubuntu: 18.04
Command: docker-compose up --build

**Comment by josephmachado** [comment]
Hmm that error happens when paths are not the same as in the repo. Did you move any files around?
Are you in the `online_store` directory?
Also can you use the make command as `make restart` and see the logs using `docker logs datagenerator` ?

**Comment by mbiombani** [comment]
I found the error

Before :
in online_store/container/datagenerator/Dockerfile

COPY ../../datagenerator /opt/dagster/datagenerator


After :
in online_store/container/datagenerator/Dockerfile
replaced by
COPY ./datagenerator /opt/dagster/datagenerator


same thing in the online_store/container/risk_api/Dockerfile folder

same for online_store/container/dagster/Dockerfile, user-code, formatter
