### ISSUE TITLE
Error response from daemon: Get "https://quay.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by Waynehsu1128** [josephmachado/online_store#3]
I have followed the step of:
1. run the git clone https://github.com/josephmachado/online_store.git  command and go to the online_store project directory using cd online_store and 
2. run make up
But I have come across this error when running make up:
`Error response from daemon: Get "https://quay.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`
And running "docker ps", it only shows:
`CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES`
but no dagster.
Please help! If you need more information I am happy to provide.

**Comment by josephmachado** [comment]
Hi @Waynehsu1128  This seems to be an issue with your docker login. Can you 
1. Ensure you have [Docker](https://docs.docker.com/engine/install/) and [Docker Compose](https://docs.docker.com/compose/install/) v1.27.0 or greater
2. This seems to be an issue with docker connection, can you try pulling any docker image `docker pull postgres` and checking out this [forum post](https://forums.docker.com/t/docker-pull-results-in-request-canceled-while-waiting-for-connection-client-timeout-exceeded-while-awaiting-headers/73064)

**Comment by Waynehsu1128** [comment]
@josephmachado Thanks for responding, I have figured out it was a DNS issue.
